import { ImageResponse } from "next/og";
import { siteConfig } from "@/lib/site";

export const runtime = "edge";
export const alt = "N2K Labs — Digital Solutions That Elevate";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * Dynamic Open Graph image (1200×630).
 *
 * Generated at the edge using Next.js's ImageResponse. Renders a branded
 * card with the N2K Labs logo, tagline, and accent color. Used by
 * openGraph.images and twitter.images in layout.tsx metadata.
 *
 * URL: /opengraph-image.png (auto-generated by Next.js)
 */
export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-start",
          justifyContent: "center",
          background: "#0a0a0c",
          padding: "80px",
          position: "relative",
          fontFamily: "system-ui, sans-serif",
        }}
      >
        {/* Grid background */}
        <div
          style={{
            position: "absolute",
            inset: 0,
            backgroundImage:
              "linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px)",
            backgroundSize: "40px 40px",
          }}
        />
        {/* Accent glow */}
        <div
          style={{
            position: "absolute",
            top: "-20%",
            right: "-10%",
            width: "600px",
            height: "600px",
            borderRadius: "50%",
            background:
              "radial-gradient(circle, rgba(0,212,255,0.15), transparent 70%)",
          }}
        />

        {/* Mono label */}
        <div
          style={{
            display: "flex",
            fontSize: 20,
            letterSpacing: "0.4em",
            color: "#00d4ff",
            textTransform: "uppercase",
            marginBottom: 24,
            fontFamily: "monospace",
          }}
        >
          N2K / Labs
        </div>

        {/* Logo */}
        <div
          style={{
            display: "flex",
            fontSize: 96,
            fontWeight: 900,
            color: "#f0ece6",
            letterSpacing: "-0.04em",
            marginBottom: 24,
          }}
        >
          N2K
          <span style={{ color: "#00d4ff" }}>.</span>
        </div>

        {/* Tagline */}
        <div
          style={{
            display: "flex",
            fontSize: 36,
            color: "#8a8a93",
            fontWeight: 400,
            maxWidth: "800px",
            lineHeight: 1.3,
          }}
        >
          {siteConfig.tagline}
        </div>

        {/* Bottom bar */}
        <div
          style={{
            position: "absolute",
            bottom: 80,
            left: 80,
            right: 80,
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            borderTop: "1px solid rgba(255,255,255,0.1)",
            paddingTop: 24,
            fontSize: 18,
            color: "#5a5a63",
            fontFamily: "monospace",
          }}
        >
          <span>South Pacific · Fiji</span>
          <span>n2klabs.com</span>
        </div>
      </div>
    ),
    size,
  );
}
